#!/usr/bin/env python
#
"""
	Erlang-transmission daemon control
	
	@author Jean-Lou Dupont
"""
import os
import sys
from optparse import OptionParser

class Commands(object):
	
	@classmethod
	def start(cls, feedback):
		print "start %s" % feedback
		
	@classmethod
	def stop(cls, feedback):
		print "stop"
		


def main():
	usage= """etrx [-q] [start|stop] 
"""
	
	parser=OptionParser(usage)
	parser.add_option("-q", "--quiet",
                  action="store_false", dest="feedback", default=True,
                  help="don't print status messages to stdout")
                  
	(options, args) = parser.parse_args()
    
	if len(args) != 1:
		parser.error("incorrect number of arguments")
      
	cmd = args[0]
	feedback = options.feedback
	
	try:
		getattr(Commands(), cmd)(feedback)
	except:
		print "! invalid command [%s]\n" % cmd

	
if __name__=="__main__":
	main()
