#!/usr/bin/env escript
%% -*- erlang -*-
%%! -sname etrx
%%
%% @author Jean-Lou Dupont
%%

err_lib() -> "erlang-transmission not found".
err_cmd() -> "unknown command: ".

main([]) ->
	main([start]);

main(["stop"]) ->
	err("stop?");
	

main([start]) ->
	code:add_pathsa(["./ebin"]),
	
	try
		%%io:format("Node[~s]~n", [node()]),
		Status = transmission_admin:daemon(status),
		%%io:format("status[~p]~n", [Status])

		case Status of
		 
			rpcerror ->
				trystart();
				
			{pid, Pid} ->
				msg("daemon running, pid:", Pid)	
				
		end

		
	catch
	
		error:undef ->
			err(err_lib());
		
		X:Y ->
			io:format("X[~p] Y[~p]~n", [X,Y]),
			halt(1)

	end;
	
	
main([NA]) ->
	err(err_cmd(), NA).


trystart() ->
	ok.
	
	
err(Msg) ->
	io:format("etrx: ~s~n", [Msg]),
	halt(1).
	
err(Msg1, Msg2) ->
	io:format("etrx: ~s~s~n", [Msg1, Msg2]),
	halt(1).

%%msg(Msg) ->
%%	io:format("etrx: ~s~n", [Msg]),
%%	halt(0).
	
msg(Msg1, Msg2) ->
	io:format("etrx: ~s~s~n", [Msg1, Msg2]),
	halt(0).